### ISSUE TITLE
Analizar y crear los índices en mongodb

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/db-plugins#82]
Revisar los casos de uso descritos en https://github.com/alercebroker/usecases y asegurar que los índices cubren esas consultas.

- Agregar configuración de mongodb para tirar error con consultas que no usan índice dentro de los tests de integración de los steps (sorting-hat, scribe, lightcurve)

```[tasklist]
### Tasks
- [ ] https://github.com/alercebroker/db-plugins/issues/84
- [ ] https://github.com/alercebroker/sorting_hat_step/issues/78
- [ ] https://github.com/alercebroker/lightcurve-step/issues/38
- [ ] https://github.com/alercebroker/db-plugins/issues/87
- [ ] https://github.com/alercebroker/db-plugins/issues/88
``` 

Criterio de aceptación:
- Indices creados para Elasticc y Staging
- Docker compose de cada step con la configuración "no index" de mongodb
